services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8008"
    container_name: suga_watako_django_app
    command: python manage.py runserver 0.0.0.0:8008
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${USER_PASS}
      - POSTGRES_DB=${USER_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol: