services:
  web:
    # ディレクトリ（.）にあるDockerfileを使用してコンテナイメージをビルドする
    build:
      context: .
      dockerfile: dockerfile
    # ボリュームの設定を行うために記述する
    volumes:
      - .:/app
    # host_port:container_portという表現で、これにより、コンテナ内のアプリケーションが外部からアクセス可能となる
    ports:
      - "8000:8000"
    container_name: my-django-app
    command: python manage.py runserver 0.0.0.0:8000
    # 依存しているサービスが起動している場合にのみ起動（下記はDBが起動してwebが起動という意味）
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"